$activeBorderColor = rgba(00000000)
$inactiveBorderColor = rgba(00000000)
$activeShadowColor = rgba(88ff66ff)
$inactiveShadowColor = rgba(26ff66ff)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    shadow {
        enabled = true
        color = $activeShadowColor
        color_inactive = $inactiveShadowColor
    }
}
