#   ____  __  ______   __________  _   __#
#  / __ \/  |/  /   | / ____/ __ \/ | / /#
# / / / / /|_/ / /| |/ /   / / / /  |/ / #
#/ /_/ / /  / / ___ / /___/ /_/ / /|  /  #
#\____/_/  /_/_/  |_\____/\____/_/ |_/   

general {
    col.active_border = rgba(00000000)
    col.inactive_border = rgba(00000000)
    border_size = 0
}

group {
    col.border_active = rgba(00000000)
    col.border_inactive = rgba(00000000)
}

decoration {
    rounding = 6
    active_opacity = 0.95
    inactive_opacity = 0.85

    shadow {
        enabled = true
        range = 80
        render_power = 2
        color = 0xFFF200F3
        color_inactive = 0x99ffaacc
    }

    blur {
        enabled = true
        size = 8
        passes = 3
        noise = 0.03
        contrast = 1.07
        brightness = 0.83
        vibrancy = 0.23
        vibrancy_darkness = 0.75
    }
}



