background            #130c2b
foreground            #f5caff

# black
color0  #130c2b
color8  #9e9e9e

# red
color1  #ff66ff
color9  #ff80ff

# green
color2  #8563ff
color10 #ac7dff

# yellow
color3  #ff66ff
color11 #ff80ff

# blue
color4  #8467ff
color12 #ab82ff

# magenta
color5  #ff66ff
color13 #ff80ff

#cyan
color6  #8361ff
color14 #aa7bff

#white
color7  #f5caff
color15 #ffffff


