[colors]
[colors.primary]
background = "#130c2b"
foreground = "#ffb3ff"

[colors.normal]
black   = "#130c2b"
red     = "#ff66ff"
green   = "#8563ff"
yellow  = "#ff66ff"
blue    = "#8467ff"
magenta = "#ff66ff"
cyan    = "#8361ff"
white   = "#ffb3ff"

[colors.bright]
black   = "#ffa8fc"
red     = "#ff80ff"
green   = "#ac7dff"
yellow  = "#ff80ff"
blue    = "#ab82ff"
magenta = "#ff80ff"
cyan    = "#aa7bff"
white   = "#ffc7ee"

[colors.cursor]
text   = "#130c2b"
cursor = "#ffb3ff"
