# Background and foreground colors
background = #130c2b
foreground = #ffb3ff

# Standard colors
palette = 0=#130c2b
palette = 1=#ff66ff
palette = 2=#8563ff
palette = 3=#ff66ff
palette = 4=#8467ff
palette = 5=#ff66ff
palette = 6=#8361ff
palette = 7=#ffb3ff

# Bright colors
palette = 8=#ffa8fc
palette = 9=#ff80ff
palette = 10=#ac7dff
palette = 11=#ff80ff
palette = 12=#ab82ff
palette = 13=#ff80ff
palette = 14=#aa7bff
palette = 15=#ffc7ee
